### ISSUE TITLE
Jareg A2 does not track ally protect

### ISSUE THREAD

**Issue by fulkers** [DeadwoodJedi/speed-calculator-bug-tracker#16]
Seems like Jareg's A2 tracks increase defense, but not the ally protect portion.

**Comment by mitchelkuijpers** [comment]
Hi @fulkers,

Please don't assign Deadwoodjedi (he is busy enough) and use the bug templates. I just checked and  Jareg seems to track both as you can see in this screenshot:

![image](https://user-images.githubusercontent.com/621140/105682178-67b5db00-5ef2-11eb-8a7d-05898b73a17a.png)

I will close this since I don't see any bug. If you think this is invalid please feel tree to give me more information here.

**Comment by fulkers** [comment]
Thank you! Sorry for my mistake. Really love the new tools.
rich
