### ISSUE TITLE
Fahrakin the Fat A3 not interacting with A1 of other Champions (ie Pain Keeper)

### ISSUE THREAD

**Issue by JatzCracker** [DeadwoodJedi/speed-calculator-bug-tracker#18]
Fahrakin the Fat A3 skill (Beatdown) where all other ally champions attack the target enemy with their default A1. The calculator does not integrate the turn meter effects of these A1 skills such as Pain Keeper (Fills turn meter by 10%).

Important for Unkillable teams :D

**Comment by mitchelkuijpers** [comment]
Do you have a actual bugreport with details that prove that this is not working? Because if you look at this video for example you'll see that it does: https://www.youtube.com/watch?v=nv1X3ZrL4Gk&t=335s

I am going to close this issue since there are not any details that make me think this is not working.
