### ISSUE TITLE
fail turn simulation for CB on hard 

### ISSUE THREAD

**Issue by eisivictor** [DeadwoodJedi/speed-calculator-bug-tracker#21]
i used the CB simulator for hard CB

the simulator is incorrect and gave the wrong turns around turn 9-10.
pain keeper took an extra turn where it shouldn't and thus it got out of sync 
I run the simulation with 
pain keeper (lead): 171 spd
maneater: 179 spd

**Comment by RoboHoboBobo** [comment]
Since you simulated with only two champions, did you also do the run in-game with only two champions?

**Comment by eisivictor** [comment]
i did with a full team
i also did the exact simulation and still it wasnt accurate

does the number of players affect the timing?

‫בתאריך יום ג׳, 26 בינו׳ 2021 ב-23:38 מאת ‪RoboHoboBobo‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by mitchelkuijpers** [comment]
Yes the number of player affects the timing.

**Comment by mitchelkuijpers** [comment]
I'll close this issue now unless you have a full bug report. With speeds of all 5 champions and a something to prove it isn't working correctly.

**Comment by eisivictor** [comment]
i have this configuration and i just did a run with me manually doing each
step as stated in the simulator
i think things started to get askew on turn 5 when maneater was the last
champion before the CB, and he should have gotten his turn only on round 6

‫בתאריך יום ד׳, 27 בינו׳ 2021 ב-23:18 מאת ‪Mitchel Kuijpers‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by mitchelkuijpers** [comment]
Did you input all speeds in the calculator with all things like speeds sets and lore of steel properly configured? Because only putting in two champions wont work as stated by @RoboHoboBobo . Please fill in all **5** champions an test out if it's incorrect (which I highly doubt) Also check if you don't have any TM increasing masteries which might throw off the tune.

If it's still not working as expected then I need way more information than only the speeds of two champions, I would need the following information:

1. True speed of all 5 champions
2. screenshots of the masteries of all 5 champions (to rule out TM increasing masteries). '
3. A video from turn 0 till the turn where it proves that the speed calculator is wrong.
4. And just to be be thorough I want screenshots of all 5 champions where I can see the gear and the stats.
