### ISSUE TITLE
Nightmare Speed

### ISSUE THREAD

**Issue by Arazern** [DeadwoodJedi/speed-calculator-bug-tracker#25]
Hi,
Pretty sure the game speed for nightmare has changed, yesterday the order worked fine up to 50th level, now the maneaters are out of sync with the clan boss. Can the spead on the calculator be updated to the new speed.

Regards Arazern

**Comment by mitchelkuijpers** [comment]
Hi Arazern, the speed of the NM clan boss most definitely hasn't changed. Are you saying that your speeds don't work ingame anymore? Make sure to check if you haven't changed any masteries or changed  any gear which might have changed your true speed.

Also you might use the website from DeadwoodJedi to check your tunes: https://www.deadwoodjedi.com/speed-tunes-7/x

I'll close this issue now since the NM speed hasn't changed, if you need help with your maneater team please don't use this bug tracker for that. But join DeadwoodJedi's discord or check out the above link I gave you.
