### ISSUE TITLE
Warcaster + Renegade Comp

### ISSUE THREAD

**Issue by Gcvanasel** [DeadwoodJedi/speed-calculator-bug-tracker#5]
UMN/NM both workout

Lead  : Skullcrusher - 240, 2 Speed sets and LoS
1st C  : Seeker - 245, 3 Speed sets and LoS
2nd C : Aina - 222, 1 Speed set No LoS
3rd C : Warcaster - 268, 3 Speed sets and LoS
4th C : Renegade - 240, 1 Speed set and LoS 

I have been running this comp for the past few days and Warcaster will cast the Block Damage before each AOE. Please check the calculator as I am sure it's a mild tweak

**Comment by mitchelkuijpers** [comment]
Hi,

Did you by any chance forgot the right delay for seeker? Because if put the delay on 3 for the seeker his A2 I get this result:

![image](https://user-images.githubusercontent.com/621140/105091192-c2d57100-5a9f-11eb-96c2-1c0919c8070f.png)

**Comment by Gcvanasel** [comment]
Hi,

This is a full auto team from the start

Regards

Christiaan

**Comment by mitchelkuijpers** [comment]
Hi @Gcvanasel,

I just filled in the comp and saved so that will make it a bit easier to look into this: https://deadwoodjedi.info/cb/a49cfd52d3e3a1a4d1115972a37a26c5ec56ac13

Could you send me screenshots of your champs their stats, and their masteries?

Also if it's possible could you do a CB run and check if in our calculator they are using the same skills as in the calculator

**Comment by Foxur-g** [comment]
If i'm not wrong, since the update site, teams with seeker aren't working on the calculator well. because now it says that  hit 2 times and in the other calculator it used to say that hit 1 time 
![unknown-5](https://user-images.githubusercontent.com/77753138/105230772-288c3080-5b66-11eb-9a1c-c49fd1f134de.png)
![unknown-4](https://user-images.githubusercontent.com/77753138/105230774-29bd5d80-5b66-11eb-994d-f80a2d66389e.png)
![image](https://user-images.githubusercontent.com/77753138/105230827-3fcb1e00-5b66-11eb-8767-5c27f9113678.png)

**Comment by RoboHoboBobo** [comment]
Renegade 2:1 comps usually have a partially-booked Renegade, so her A3 is a 6-turn cooldown.

**Comment by mitchelkuijpers** [comment]
Ah so the problem was that the cooldown was wrongly configured? Because I updated it and changing it to a 6 turn cooldown seems to work: https://deadwoodjedi.info/cb/f7824800a2abb876fef952e9e78b13795aba056e. 

I'll close this issue then. Thank you for getting back to me, much appreciated.

**Comment by mitchelkuijpers** [comment]
I now noticed this is solved by @RoboHoboBobo much appreciated man!

**Comment by Gcvanasel** [comment]
Hi,

Apologies for coming to the party so late,

Thanks @RoboHoboBobo that was the missing piece, completely forgot about that.

You may close this ticket and apologies for not paying attention

Christiaan
